# Generated by Django 4.2.11 on 2024-04-14 10:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_resource_comment_photo_alter_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
