# Generated by Django 4.2.11 on 2024-04-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_resource_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='link_url',
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.resource')),
            ],
        ),
    ]
