# Generated by Django 4.2.11 on 2024-04-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_remove_resourcelink_resource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(default="gentle parenting", max_length=200),
        ),
    ]
